apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: hackathonParis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: hackathonParis.registry.io/app:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-configmap
        - secretRef:
            name: app-secret
