apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: hackathonParis
spec:
  rules:
  - host: "app.hackathonParis.io"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: app-service
            port:
              number: 3000
